# Create subfolder within the current working directory
dir.create("R")
dir.create("R/Meteorology")
dir.create("R/PufPasEffectiveVolume")
dir.create("Data")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/isd_light")
dir.create("Output/Data/MERRA")
dir.create("Output/Data/Results")
dir.create("Output/Data/Results/isd_light")
dir.create("Output/Data/Results/MERRA")